### ISSUE TITLE
couldnt find in octobercms

### ISSUE THREAD

**Issue by JFOC** [MatissJanis/oc-mail#1]
plugin is not found in octobercms site

**Comment by MatissJanis** [comment]
It's because It hasn't been published yet. Just hang in there. Hopefully it will be there next week.

**Comment by JFOC** [comment]
Thanks @MatissJanis

**Comment by MatissJanis** [comment]
The plugin has now been released: http://octobercms.com/plugin/mja-mail
Cheers!
