### ISSUE TITLE
Unexpected Type of Array Error When Using w/ Contact Plugin

### ISSUE THREAD

**Issue by abass** [MatissJanis/oc-mail#11]
You can see the comment thread that I discussed with the other plugin developer here:

[Contact Plugin - "Unexpected Type of Array Error"](http://octobercms.com/plugin/fabriciorabelo-contact/unexpected-type-of-array-error?page=1#post-6953)

When I have this plugin enabled and paired up with the [Contact Plugin](http://octobercms.com/plugin/fabriciorabelo-contact) I get the error message:

> "Unexpected type of array, should attribute "reply_to" be jsonable?" on line 1064 of vendor/october/rain/src/databse/model.php

Upon disabling this plugin, the contact form worked perfectly fine. It is assumed that this plugin would be used in pair with a contact form plugin and the contact plugin linked appears to be the most popular so hopefully this can get resolved.

Thanks so much for this plugin, it really is phenomenal!

**Comment by MatissJanis** [comment]
Thanks for letting me know about this bug! I have fixed it now :+1:

**Comment by abass** [comment]
Awesome! Thanks for such a quick reply and fix! Really appreciate it, killer plugin, keep up the awesome work!
