### ISSUE TITLE
Exception Thrown After Updating to Build 289

### ISSUE THREAD

**Issue by abass** [MatissJanis/oc-mail#14]
Since updating, I am now getting this exception error when I click on the "Mail log" on the backend.

![IMG](https://s3.amazonaws.com/f.cl.ly/items/3I3u352F3o1Q0Y1o0f2J/Image%202015-08-10%20at%201.29.58%20AM.png)

Bit late for me right now, I'll look into it a bit more to see if it's on my end or the plugin's end. It just started happening after updating to the most recent build of October though so I'm assuming it's the Plugin?

**Comment by MatissJanis** [comment]
Thanks :+1:
