### ISSUE TITLE
Does not install in sqlite because the alter table statement is not supported by sqlite

### ISSUE THREAD

**Issue by aydancoskun** [MatissJanis/oc-mail#16]
I am getting:

"SQLSTATE[HY000]: General error: 1 near "MODIFY": syntax error (SQL: ALTER TABLE `mja_mail_email_log` MODIFY `code` VARCHAR(255) NULL;)" on line 624 of /home/staffcheck/staffcheck-web/vendor/laravel/framework/src/Illuminate/Database/Connection.php

https://www.sqlite.org/lang_altertable.html
 the problems are in 
make_body_column_nullable.php & make_code_column_nullable.php

The following statements are not supported by sqlite
DB::statement('ALTER TABLE `mja_mail_email_log` MODIFY `body` text COLLATE utf8_unicode_ci NULL;');
DB::statement('ALTER TABLE `mja_mail_email_log` MODIFY `body` text COLLATE utf8_unicode_ci NOT NULL;');
DB::statement('ALTER TABLE `mja_mail_email_log` MODIFY `code` VARCHAR(255) NULL;');
DB::statement('ALTER TABLE `mja_mail_email_log` MODIFY `code` VARCHAR(255);');

I did manage to install it by applying the changes manually in the tables, commenting all the above queries out and then running
php artisan october:up
That registered the migrations correctly but of course that might not be an option for others, especially on hosts where you don't have access to the command line.

I am trying to fix this and sent you a pull request

**Comment by MatissJanis** [comment]
Should be fixed with v1.2.1
