### ISSUE TITLE
Export Feature?

### ISSUE THREAD

**Issue by abelafonte** [MatissJanis/oc-mail#19]
Are there any plans to make an export feature for this? We need the ability to send CSV exports of form data in our projects.

**Comment by MatissJanis** [comment]
Hello!

I don't really understand how a stats plugin as this would need a data export. Could You please explain what You have in mind?

**Comment by abelafonte** [comment]
I hope I have the proper support page for the plugin I am testing.  I was looking at the logging and stats plugin for the OctoberCMS form builder.  So, basically, there is a page within this plugin that shows "logs".  This shows rows of all data that has been submitted by users. THIS is the data that we would need to export as CSV, with ability to define the date range needed to export.

**Comment by MatissJanis** [comment]
Sorry, but this is not the plugin You are referring to. :)
