### ISSUE TITLE
FormBuilder

### ISSUE THREAD

**Issue by sampoyigi** [MatissJanis/oc-mail#20]
Just wondering, does this plugin work with the FormBuilder plugin?

I have installed the plugin and it seems to be working fine without errors, but messages send from the FormBuilder does not get logged..

**Comment by MatissJanis** [comment]
Hello!

Unfortunately, FormBuilder is a paid plugin and I do not have access to it. Hence I don't know if this works well with that plugin. 

Please ask this question to the author of the FormBuilder plugin.

Thanks!
