### ISSUE TITLE
Object of class GuzzleHttp\Psr7\Response could not be converted to string

### ISSUE THREAD

**Issue by abass** [MatissJanis/oc-mail#23]
This plugin has caused quite a bit of confusion on the octoberCMS issue tracker. Many were blaming it on October when in reality it turned out to be this plugin. Please refer to this post for more information about this error:

https://github.com/octobercms/october/issues/2242

Here is the exact error that arises when submitting the contact form:

![IMG](https://d17oy1vhnax1f7.cloudfront.net/items/2R1X3v2v2F001X2p2p3O/Image%202016-08-21%20at%2010.13.38%20PM.png)

**Comment by MatissJanis** [comment]
Hello!

Thank You for letting me know about this issue! It has now been fixed.

Please let me know if You run in to any other difficulties.

**Comment by abass** [comment]
That was quick!

Thank you @MatissJanis for doing this - I'm sure you just made very many people quite happy 👍
