### ISSUE TITLE
Selecting Wrong Mail Plugin

### ISSUE THREAD

**Issue by abass** [MatissJanis/oc-mail#32]
For some reason I am getting this error:

![IMG](https://dr5mo5s7lqrtc.cloudfront.net/items/000H24103E3J2P420x2y/Image%202017-10-08%20at%206.31.18%20PM.png?X-CloudApp-Visitor-Id=51440efb07735d05d70055a92c35f59d&v=73c7032d)

When I don't even have [janvince.smallcontactform] installed anywhere. How does your plugin choose which plugin to monitor for email sending/receiving?

```
website.com/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php line 112
```

```
if (! isset($this->hints[$segments[0]])) {
    throw new InvalidArgumentException("No hint path defined for [{$segments[0]}]."); <!--LINE WITH ERROR-->
}
```

**Comment by MatissJanis** [comment]
Hello,

This plugin listens for the `mailer.prepareSend` event which is defined and called by october. See [here](https://github.com/MatissJanis/oc-mail/blob/master/Plugin.php#L85).

Closing this issue as it is unrelated to this plugin. Please contact the author of `janvince.smallcontactform` for a fix.
